services:
  eureka-server:
    build:
      context: .
      target: eureka-server
    container_name: eureka-server
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  config-server:
    build:
      context: .
      target: config-server
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  eureka-client:
    build:
      context: .
      target: eureka-client
    container_name: eureka-client
    ports:
      - "8083:8083"
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8081/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api-gateway:
    build:
      context: .
      target: api-gateway
    container_name: api-gateway
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8081/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  microservices-network:
    driver: bridge